" Name:         Purple Martin
" Version:      1.0
" Description:  A color scheme with a purple touch.
" Author:       Lucas A. Miranda <miranda.a.lucas@gmail.com>
" Maintainer:   Lucas A. Miranda <miranda.a.lucas@gmail.com>
" URL:          https://github.com/lucas-miranda/purple_martin
" License:      MIT
" Last Updated: Thu 14 Oct 2021 11:08:09 AM -03

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'purple_martin'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Boolean Constant
hi! link Character String
hi! link Debug Special
hi! link Define PreProc
hi! link ErrorMsg Error
hi! link Float Number
hi! link Include PreProc
hi! link Label Statement
hi! link PreCondit PreProc
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Structure
hi! link Tag Special
hi! link PopupSelected PmenuSel
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#07010b', '#d36355', '#86d355', '#e2e231', '#b764ec', '#fd85e7', '#11afff', '#ecf2fb', '#464c54', '#ffba30', '#51e773', '#e1f957', '#c6a7ff', '#8a82fd', '#34e9ed', '#8b8e8e']
  if has('nvim')
    let g:terminal_color_0 = '#07010b'
    let g:terminal_color_1 = '#d36355'
    let g:terminal_color_2 = '#86d355'
    let g:terminal_color_3 = '#e2e231'
    let g:terminal_color_4 = '#b764ec'
    let g:terminal_color_5 = '#fd85e7'
    let g:terminal_color_6 = '#11afff'
    let g:terminal_color_7 = '#ecf2fb'
    let g:terminal_color_8 = '#464c54'
    let g:terminal_color_9 = '#ffba30'
    let g:terminal_color_10 = '#51e773'
    let g:terminal_color_11 = '#e1f957'
    let g:terminal_color_12 = '#c6a7ff'
    let g:terminal_color_13 = '#8a82fd'
    let g:terminal_color_14 = '#34e9ed'
    let g:terminal_color_15 = '#8b8e8e'
  endif
  if get(g:, 'purple_martin_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ecf2fb guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ecf2fb guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ecf2fb guibg=#07010b gui=NONE cterm=NONE
    hi Terminal guifg=#ecf2fb guibg=#07010b gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal guifg=#464c54 guibg=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#fd85e7 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#1d1723 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#c6a7ff guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#8b8e8e guibg=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#07010b guibg=#86d355 gui=NONE cterm=NONE
  hi DiffChange guifg=#07010b guibg=#11afff gui=NONE cterm=NONE
  hi DiffDelete guifg=#07010b guibg=#d36355 gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi Directory guifg=#ecf2fb guibg=#07010b gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#ecf2fb guibg=#07010b gui=NONE cterm=NONE
  hi Exception guifg=#34e9ed guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#ecf2fb guibg=#07010b gui=NONE cterm=NONE
  hi Folded guifg=#ecf2fb guibg=#07010b gui=italic cterm=italic
  hi Function guifg=#8a82fd guibg=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#ecf2fb guibg=#07010b gui=standout cterm=reverse
  hi Keyword guifg=#34e9ed guibg=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#464c54 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg guifg=#ecf2fb guibg=#07010b gui=NONE cterm=NONE
  hi MoreMsg guifg=#ecf2fb guibg=#07010b gui=NONE cterm=NONE
  hi NonText guifg=#464c54 guibg=#07010b gui=NONE cterm=NONE
  hi Number guifg=#ffba30 guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#8b8e8e guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#c4c8ce guibg=#1d1723 gui=NONE cterm=NONE
  hi PmenuSel guifg=#1d1723 guibg=#c6a7ff gui=NONE cterm=NONE
  hi PmenuSbar guifg=#8a82fd guibg=#464c54 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#34e9ed guibg=#464c54 gui=NONE cterm=NONE
  hi Question guifg=#ecf2fb guibg=#464c54 gui=NONE cterm=NONE
  hi Repeat guifg=#fd85e7 guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=#07010b guibg=#11afff gui=NONE cterm=NONE
  hi SignColumn guifg=#ecf2fb guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#8b8e8e guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#d36355 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#b764ec gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#fd85e7 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#11afff gui=reverse,undercurl ctermfg=NONE ctermbg=NONE cterm=reverse,undercurl
  hi StatusLine guifg=NONE guibg=#464c54 gui=NONE cterm=NONE
  hi StatusLineNC guifg=NONE guibg=#07010b gui=NONE cterm=NONE
  hi String guifg=#86d355 guibg=NONE gui=NONE cterm=NONE
  hi Structure guifg=#34e9ed guibg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#464c54 guibg=#07010b gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#07010b gui=NONE cterm=NONE
  hi TabLineSel guifg=#b764ec guibg=#ecf2fb gui=NONE cterm=NONE
  hi Title guifg=#b764ec guibg=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#464c54 guibg=NONE gui=NONE cterm=NONE
  hi Visual guifg=#07010b guibg=#c6a7ff gui=NONE cterm=NONE
  hi VisualNOS guifg=#07010b guibg=#fd85e7 gui=NONE cterm=NONE
  hi WarningMsg guifg=#07010b guibg=#e2e231 gui=NONE cterm=NONE
  hi WildMenu guifg=#c6a7ff guibg=#07010b gui=NONE cterm=NONE
  hi Comment guifg=#464c54 guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#11afff guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#07010b guibg=#d36355 gui=NONE cterm=NONE
  hi Identifier guifg=#ecf2fb guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#ecf2fb guibg=#07010b gui=NONE cterm=NONE
  hi Macro guifg=#8a82fd guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#8b8e8e guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#51e773 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#34e9ed guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#c6a7ff guibg=NONE gui=bold cterm=bold
  hi Type guifg=#b764ec guibg=NONE gui=bold cterm=bold
  hi Typedef guifg=#11afff guibg=NONE gui=bold cterm=bold
  hi Underlined guifg=NONE guibg=NONE guisp=#51e773 gui=italic,underline ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi CursorIM guifg=NONE guibg=NONE gui=inverse ctermfg=NONE ctermbg=NONE cterm=inverse
  hi ToolbarLine guifg=NONE guibg=#07010b gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ecf2fb guibg=#07010b gui=bold cterm=bold
  hi TelescopeSelection guifg=#c6a7ff guibg=NONE gui=NONE cterm=NONE
  hi TelescopeSelectionCaret guifg=#fd85e7 guibg=NONE gui=NONE cterm=NONE
  hi TelescopeMultiSelection guifg=#c6a7ff guibg=NONE gui=NONE cterm=NONE
  hi TelescopeNormal guifg=NONE guibg=#07010b gui=NONE cterm=NONE
  hi TelescopeMatching guifg=#86d355 guibg=NONE gui=NONE cterm=NONE
  hi TelescopePromptPrefix guifg=#b764ec guibg=NONE gui=NONE cterm=NONE
  hi TelescopeBorder guifg=#8b8e8e guibg=NONE gui=NONE cterm=NONE
  hi! link TelescopePromptBorder TelescopeBorder
  hi! link TelescopeResultsBorder TelescopeBorder
  hi! link TelescopePreviewBorder TelescopeBorder
  hi CmpItemAbbr guifg=#8b8e8e guibg=NONE gui=NONE cterm=NONE
  hi CmpItemAbbrMatch guifg=#ecf2fb guibg=NONE gui=bold cterm=bold
  hi CmpItemKind guifg=#b764ec guibg=NONE gui=NONE cterm=NONE
  hi CmpItemMenu guifg=#e1f957 guibg=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Underlined gui=underline cterm=underline
  endif

  " Terminal
  " ------------- "

  if has('nvim')
    let g:terminal_color_0 = '#07010b'
    let g:terminal_color_1 = '#d36355'
    let g:terminal_color_2 = '#86d355'
    let g:terminal_color_3 = '#e2e231'
    let g:terminal_color_4 = '#b764ec'
    let g:terminal_color_5 = '#fd85e7'
    let g:terminal_color_6 = '#11afff'
    let g:terminal_color_7 = '#ecf2fb'
    let g:terminal_color_8 = '#464c54'
    let g:terminal_color_9 = '#ffba30'
    let g:terminal_color_10 = '#51e773'
    let g:terminal_color_11 = '#e1f957'
    let g:terminal_color_12 = '#c6a7ff'
    let g:terminal_color_13 = '#8a82fd'
    let g:terminal_color_14 = '#34e9ed'
    let g:terminal_color_15 = '#8b8e8e'
    let g:terminal_color_background = '#07010b'
    let g:terminal_color_foreground = '#ecf2fb'
  else
    let g:terminal_ansi_colors = [
          \ '#07010b',
          \ '#d36355',
          \ '#86d355',
          \ '#e2e231',
          \ '#b764ec',
          \ '#fd85e7',
          \ '#11afff',
          \ '#ecf2fb',
          \ '#464c54',
          \ '#ffba30',
          \ '#51e773',
          \ '#e1f957',
          \ '#c6a7ff',
          \ '#8a82fd',
          \ '#34e9ed',
          \ '#8b8e8e'
          \ ]
  endif

  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'purple_martin_transp_bg', 0)
    hi Normal ctermfg=254 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=254 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=254 ctermbg=232 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=254 ctermbg=232 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=238 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=212 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi CursorLineNr ctermfg=183 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=245 ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=232 ctermbg=113 cterm=NONE
  hi DiffChange ctermfg=232 ctermbg=39 cterm=NONE
  hi DiffDelete ctermfg=232 ctermbg=167 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=NONE cterm=bold
  hi Directory ctermfg=254 ctermbg=232 cterm=NONE
  hi EndOfBuffer ctermfg=254 ctermbg=232 cterm=NONE
  hi Exception ctermfg=44 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=254 ctermbg=232 cterm=NONE
  hi Folded ctermfg=254 ctermbg=232 cterm=italic
  hi Function ctermfg=105 ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=254 ctermbg=232 cterm=reverse
  hi Keyword ctermfg=44 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=238 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=254 ctermbg=232 cterm=NONE
  hi MoreMsg ctermfg=254 ctermbg=232 cterm=NONE
  hi NonText ctermfg=238 ctermbg=232 cterm=NONE
  hi Number ctermfg=214 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=245 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=251 ctermbg=234 cterm=NONE
  hi PmenuSel ctermfg=234 ctermbg=183 cterm=NONE
  hi PmenuSbar ctermfg=105 ctermbg=238 cterm=NONE
  hi PmenuThumb ctermfg=44 ctermbg=238 cterm=NONE
  hi Question ctermfg=254 ctermbg=238 cterm=NONE
  hi Repeat ctermfg=212 ctermbg=NONE cterm=NONE
  hi Search ctermfg=232 ctermbg=39 cterm=NONE
  hi SignColumn ctermfg=254 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=245 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=reverse,undercurl
  hi StatusLine ctermfg=NONE ctermbg=238 cterm=NONE
  hi StatusLineNC ctermfg=NONE ctermbg=232 cterm=NONE
  hi String ctermfg=113 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=44 ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=238 ctermbg=232 cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=232 cterm=NONE
  hi TabLineSel ctermfg=135 ctermbg=254 cterm=NONE
  hi Title ctermfg=135 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=238 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=232 ctermbg=183 cterm=NONE
  hi VisualNOS ctermfg=232 ctermbg=212 cterm=NONE
  hi WarningMsg ctermfg=232 ctermbg=184 cterm=NONE
  hi WildMenu ctermfg=183 ctermbg=232 cterm=NONE
  hi Comment ctermfg=238 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=39 ctermbg=NONE cterm=NONE
  hi Error ctermfg=232 ctermbg=167 cterm=NONE
  hi Identifier ctermfg=254 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=254 ctermbg=232 cterm=NONE
  hi Macro ctermfg=105 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=245 ctermbg=NONE cterm=NONE
  hi Special ctermfg=78 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=44 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=183 ctermbg=NONE cterm=bold
  hi Type ctermfg=135 ctermbg=NONE cterm=bold
  hi Typedef ctermfg=39 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=inverse
  hi ToolbarLine ctermfg=NONE ctermbg=232 cterm=NONE
  hi ToolbarButton ctermfg=254 ctermbg=232 cterm=bold
  hi TelescopeSelection ctermfg=183 ctermbg=NONE cterm=NONE
  hi TelescopeSelectionCaret ctermfg=212 ctermbg=NONE cterm=NONE
  hi TelescopeMultiSelection ctermfg=183 ctermbg=NONE cterm=NONE
  hi TelescopeNormal ctermfg=NONE ctermbg=232 cterm=NONE
  hi TelescopeMatching ctermfg=113 ctermbg=NONE cterm=NONE
  hi TelescopePromptPrefix ctermfg=135 ctermbg=NONE cterm=NONE
  hi TelescopeBorder ctermfg=245 ctermbg=NONE cterm=NONE
  hi! link TelescopePromptBorder TelescopeBorder
  hi! link TelescopeResultsBorder TelescopeBorder
  hi! link TelescopePreviewBorder TelescopeBorder
  hi CmpItemAbbr ctermfg=245 ctermbg=NONE cterm=NONE
  hi CmpItemAbbrMatch ctermfg=254 ctermbg=NONE cterm=bold
  hi CmpItemKind ctermfg=135 ctermbg=NONE cterm=NONE
  hi CmpItemMenu ctermfg=191 ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Underlined cterm=underline
  endif

  " Terminal
  " ------------- "

  if has('nvim')
    let g:terminal_color_0 = '#07010b'
    let g:terminal_color_1 = '#d36355'
    let g:terminal_color_2 = '#86d355'
    let g:terminal_color_3 = '#e2e231'
    let g:terminal_color_4 = '#b764ec'
    let g:terminal_color_5 = '#fd85e7'
    let g:terminal_color_6 = '#11afff'
    let g:terminal_color_7 = '#ecf2fb'
    let g:terminal_color_8 = '#464c54'
    let g:terminal_color_9 = '#ffba30'
    let g:terminal_color_10 = '#51e773'
    let g:terminal_color_11 = '#e1f957'
    let g:terminal_color_12 = '#c6a7ff'
    let g:terminal_color_13 = '#8a82fd'
    let g:terminal_color_14 = '#34e9ed'
    let g:terminal_color_15 = '#8b8e8e'
    let g:terminal_color_background = '#07010b'
    let g:terminal_color_foreground = '#ecf2fb'
  else
    let g:terminal_ansi_colors = [
          \ '#07010b',
          \ '#d36355',
          \ '#86d355',
          \ '#e2e231',
          \ '#b764ec',
          \ '#fd85e7',
          \ '#11afff',
          \ '#ecf2fb',
          \ '#464c54',
          \ '#ffba30',
          \ '#51e773',
          \ '#e1f957',
          \ '#c6a7ff',
          \ '#8a82fd',
          \ '#34e9ed',
          \ '#8b8e8e'
          \ ]
  endif

  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 16
  if get(g:, 'purple_martin_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Grey ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=Black ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi DiffDelete ctermfg=Black ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=NONE cterm=bold
  hi Directory ctermfg=White ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=White ctermbg=Black cterm=NONE
  hi Exception ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=White ctermbg=Black cterm=NONE
  hi Folded ctermfg=White ctermbg=Black cterm=italic
  hi Function ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=White ctermbg=Black cterm=reverse
  hi Keyword ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=White ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=White ctermbg=Black cterm=NONE
  hi NonText ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi Number ctermfg=Red ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=DarkGrey ctermbg=Blue cterm=NONE
  hi PmenuSbar ctermfg=Magenta ctermbg=DarkGrey cterm=NONE
  hi PmenuThumb ctermfg=Cyan ctermbg=DarkGrey cterm=NONE
  hi Question ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi Repeat ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Search ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi SignColumn ctermfg=White ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Grey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=reverse,undercurl
  hi StatusLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi StatusLineNC ctermfg=NONE ctermbg=Black cterm=NONE
  hi String ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=DarkBlue ctermbg=White cterm=NONE
  hi Title ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=Black ctermbg=Blue cterm=NONE
  hi VisualNOS ctermfg=Black ctermbg=DarkMagenta cterm=NONE
  hi WarningMsg ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi WildMenu ctermfg=Blue ctermbg=Black cterm=NONE
  hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Constant ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Error ctermfg=Black ctermbg=DarkRed cterm=NONE
  hi Identifier ctermfg=White ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=Black cterm=NONE
  hi Macro ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Special ctermfg=Green ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Blue ctermbg=NONE cterm=bold
  hi Type ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Typedef ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=inverse
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi TelescopeSelection ctermfg=Blue ctermbg=NONE cterm=NONE
  hi TelescopeSelectionCaret ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi TelescopeMultiSelection ctermfg=Blue ctermbg=NONE cterm=NONE
  hi TelescopeNormal ctermfg=NONE ctermbg=Black cterm=NONE
  hi TelescopeMatching ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi TelescopePromptPrefix ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi TelescopeBorder ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link TelescopePromptBorder TelescopeBorder
  hi! link TelescopeResultsBorder TelescopeBorder
  hi! link TelescopePreviewBorder TelescopeBorder
  hi CmpItemAbbr ctermfg=Grey ctermbg=NONE cterm=NONE
  hi CmpItemAbbrMatch ctermfg=White ctermbg=NONE cterm=bold
  hi CmpItemKind ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi CmpItemMenu ctermfg=Yellow ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Underlined cterm=underline
  endif

  " Terminal
  " ------------- "

  if has('nvim')
    let g:terminal_color_0 = '#07010b'
    let g:terminal_color_1 = '#d36355'
    let g:terminal_color_2 = '#86d355'
    let g:terminal_color_3 = '#e2e231'
    let g:terminal_color_4 = '#b764ec'
    let g:terminal_color_5 = '#fd85e7'
    let g:terminal_color_6 = '#11afff'
    let g:terminal_color_7 = '#ecf2fb'
    let g:terminal_color_8 = '#464c54'
    let g:terminal_color_9 = '#ffba30'
    let g:terminal_color_10 = '#51e773'
    let g:terminal_color_11 = '#e1f957'
    let g:terminal_color_12 = '#c6a7ff'
    let g:terminal_color_13 = '#8a82fd'
    let g:terminal_color_14 = '#34e9ed'
    let g:terminal_color_15 = '#8b8e8e'
    let g:terminal_color_background = '#07010b'
    let g:terminal_color_foreground = '#ecf2fb'
  else
    let g:terminal_ansi_colors = [
          \ '#07010b',
          \ '#d36355',
          \ '#86d355',
          \ '#e2e231',
          \ '#b764ec',
          \ '#fd85e7',
          \ '#11afff',
          \ '#ecf2fb',
          \ '#464c54',
          \ '#ffba30',
          \ '#51e773',
          \ '#e1f957',
          \ '#c6a7ff',
          \ '#8a82fd',
          \ '#34e9ed',
          \ '#8b8e8e'
          \ ]
  endif

  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'purple_martin_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Conceal ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Grey ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=Black ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi DiffDelete ctermfg=Black ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=NONE cterm=bold
  hi Directory ctermfg=White ctermbg=Black cterm=NONE
  hi EndOfBuffer ctermfg=White ctermbg=Black cterm=NONE
  hi Exception ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=White ctermbg=Black cterm=NONE
  hi Folded ctermfg=White ctermbg=Black cterm=italic
  hi Function ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=White ctermbg=Black cterm=reverse
  hi Keyword ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi ModeMsg ctermfg=White ctermbg=Black cterm=NONE
  hi MoreMsg ctermfg=White ctermbg=Black cterm=NONE
  hi NonText ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi Number ctermfg=Red ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Grey ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=DarkGrey ctermbg=Blue cterm=NONE
  hi PmenuSbar ctermfg=Magenta ctermbg=DarkGrey cterm=NONE
  hi PmenuThumb ctermfg=Cyan ctermbg=DarkGrey cterm=NONE
  hi Question ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi Repeat ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Search ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi SignColumn ctermfg=White ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Grey ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=reverse,undercurl
  hi StatusLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi StatusLineNC ctermfg=NONE ctermbg=Black cterm=NONE
  hi String ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=DarkGrey ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=NONE ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=DarkBlue ctermbg=White cterm=NONE
  hi Title ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Visual ctermfg=Black ctermbg=Blue cterm=NONE
  hi VisualNOS ctermfg=Black ctermbg=DarkMagenta cterm=NONE
  hi WarningMsg ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi WildMenu ctermfg=Blue ctermbg=Black cterm=NONE
  hi Comment ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi Constant ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Error ctermfg=Black ctermbg=DarkRed cterm=NONE
  hi Identifier ctermfg=White ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=Black cterm=NONE
  hi Macro ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Grey ctermbg=NONE cterm=NONE
  hi Special ctermfg=Green ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Blue ctermbg=NONE cterm=bold
  hi Type ctermfg=DarkBlue ctermbg=NONE cterm=bold
  hi Typedef ctermfg=DarkCyan ctermbg=NONE cterm=bold
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=italic,underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=inverse
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  hi TelescopeSelection ctermfg=Blue ctermbg=NONE cterm=NONE
  hi TelescopeSelectionCaret ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi TelescopeMultiSelection ctermfg=Blue ctermbg=NONE cterm=NONE
  hi TelescopeNormal ctermfg=NONE ctermbg=Black cterm=NONE
  hi TelescopeMatching ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi TelescopePromptPrefix ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi TelescopeBorder ctermfg=Grey ctermbg=NONE cterm=NONE
  hi! link TelescopePromptBorder TelescopeBorder
  hi! link TelescopeResultsBorder TelescopeBorder
  hi! link TelescopePreviewBorder TelescopeBorder
  hi CmpItemAbbr ctermfg=Grey ctermbg=NONE cterm=NONE
  hi CmpItemAbbrMatch ctermfg=White ctermbg=NONE cterm=bold
  hi CmpItemKind ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi CmpItemMenu ctermfg=Yellow ctermbg=NONE cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Underlined cterm=underline
  endif

  " Terminal
  " ------------- "

  if has('nvim')
    let g:terminal_color_0 = '#07010b'
    let g:terminal_color_1 = '#d36355'
    let g:terminal_color_2 = '#86d355'
    let g:terminal_color_3 = '#e2e231'
    let g:terminal_color_4 = '#b764ec'
    let g:terminal_color_5 = '#fd85e7'
    let g:terminal_color_6 = '#11afff'
    let g:terminal_color_7 = '#ecf2fb'
    let g:terminal_color_8 = '#464c54'
    let g:terminal_color_9 = '#ffba30'
    let g:terminal_color_10 = '#51e773'
    let g:terminal_color_11 = '#e1f957'
    let g:terminal_color_12 = '#c6a7ff'
    let g:terminal_color_13 = '#8a82fd'
    let g:terminal_color_14 = '#34e9ed'
    let g:terminal_color_15 = '#8b8e8e'
    let g:terminal_color_background = '#07010b'
    let g:terminal_color_foreground = '#ecf2fb'
  else
    let g:terminal_ansi_colors = [
          \ '#07010b',
          \ '#d36355',
          \ '#86d355',
          \ '#e2e231',
          \ '#b764ec',
          \ '#fd85e7',
          \ '#11afff',
          \ '#ecf2fb',
          \ '#464c54',
          \ '#ffba30',
          \ '#51e773',
          \ '#e1f957',
          \ '#c6a7ff',
          \ '#8a82fd',
          \ '#34e9ed',
          \ '#8b8e8e'
          \ ]
  endif

  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black            #07010B        232         Black
" Color: blue             #B764EC        135         DarkBlue
" Color: green            #86D355        113         DarkGreen
" Color: cyan             #11AFFF         39         DarkCyan
" Color: red              #D36355        167         DarkRed
" Color: magenta          #FD85E7        212         DarkMagenta
" Color: yellow           #E2E231        184         DarkYellow
" Color: brightwhite      #8B8E8E        245         Grey
" Color: brightblack      #464C54        238         DarkGrey
" Color: brightblue       #C6A7FF        183         Blue
" Color: brightgreen      #51E773         78         Green
" Color: brightcyan       #34E9ED         44         Cyan
" Color: brightred        #FFBA30        214         Red
" Color: brightmagenta    #8A82FD        105         Magenta
" Color: brightyellow     #E1F957        191         Yellow
" Color: white            #ECF2FB        254         White
" Color: darkwhite        #C4C8CE        251         Grey
" Color: lightblack       #1D1723        234         DarkGrey
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
